AllCops:
  Exclude:
    - .bundle/**
    - filemaker.gemspec
    - lib/filemaker/error.rb

Documentation:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

MethodLength:
  Enabled: false

LineLength:
  Max: 80