AllCops:
  Exclude:
    - .bundle/**
    - filemaker.gemspec
    - lib/filemaker/errors.rb
    - lib/generators/filemaker/model/templates/model.rb

Documentation:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

MethodLength:
  Enabled: false

LineLength:
  Max: 80

SpecialGlobalVars:
  Enabled: false

PredicateName:
  Enabled: false
